### ISSUE TITLE
create new user

### ISSUE THREAD

**Issue by weinformatics** [nturaga/rstudio-k8s#1]
Dear Author,
it works fine for me when use rstudio user which was the default. But how can I to create another new user ? The best way was to use yaml file.  Here are my yaml file.
```
apiVersion: v1
kind: Service
metadata:
  name: rstudio-service8
  labels:
    app: rstudio8
spec:
  type: NodePort
  ports:
    - port: 8787
      nodePort: 30009
      name: http
  selector:
    app: rstudio8
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800

---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: rstudio8-deployment
spec:
  selector:
    matchLabels:
      app: rstudio8
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: rstudio8
    spec:
      containers:
      - name: rstudio8
        image: registry.cn-hangzhou.aliyuncs.com/weinfo/wilistr:1.3.0
        env:
          - name: PASSWORD
            value: "cailiangliang789"
        ports:
        - containerPort: 8787
```
